name: CI of BOPTEST-Gym using GitHub Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testing
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: true
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Change permissions of repository folder
        run: chmod -R 777 /home/actions-runner/_work
      - name: List of files in the repository
        run: | 
         ls ${{ github.workspace }}
      - name: Build BOPTEST-Gym image
        run: make build-boptestgym
  test-local:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: testing
    steps:
      - name: Test local version
        run: make test-local-in-container
  test-service:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: testing
    steps:
      - name: Test service version
        run: make test-service-in-container
      